### PR TITLE
Adding LICENSE file to project.

### PR DESCRIPTION
**Pull request by kshithijiyer**

### CODE REVIEW

**Comment by olamy** [comment]
uhm license is already on all files. so no need of this

**Comment by kshithijiyer** [comment]
I feel this is needed as it is required to have a dedicated file on LICNESE.

**Comment by olamy** [comment]
required? why? as long as files have proper license it's fine. It can be a problem only if it's missing for some files.

**Comment by kshithijiyer** [comment]
You need to have one place where anyone and everyone who wants to use, work and modify the project and redistribute it. So for that reason a COPYING or LICENSE file is added.

**Pull request closed without merging**
