### PR TITLE
[JENKINS-36829] - empty rootURL incorrectly handled

### PR DESCRIPTION
**Pull request by kzantow**
On `ci.blueocean.io` there were inconsistencies in how URLs were handled, in particular the empty root URL was causing some issues. sse should also allow an empty root url, as Jenkins is typically `'/jenkins'` or `''`, if it's run at the root context (which is normal). This should fix an issue where sse would not work with normal Jenkins for this reason and align handling of these across the app.

NOTE: tests seem to be getting a URL which *does* end in a slash, unlike running Jenkins normally, so there's a bit to handle that.

Related to: https://github.com/jenkinsci/blueocean-plugin/pull/368

@reviewbybees esp. @tfennelly

### CODE REVIEW

**Comment by kzantow** [comment]
See also: https://github.com/jenkinsci/blueocean-plugin/pull/368

**Comment by tfennelly** [comment]
@kzantow nice one, thanks ... did you test this and make sure it works? I see the `package.json` version was up'd to `0.0.7` but it looks like it wasn't published to NPM yet.

**Comment by i386** [comment]
@kzantow ping - this review is still outstanding

**Comment by kzantow** [comment]
@tfennelly yes, I finally got to testing this, works properly for empty (root) URL and `/jenkins` I can publish this, but you have other changes to the SSE, maybe they can just get merged to the next NPM publish?

**Comment by tfennelly** [comment]
@kzantow sorry man .... will process this now.

**Comment by tfennelly** [comment]
🐝

**Pull request merged**
