### PR TITLE
Task/remove js test

### PR DESCRIPTION
**Pull request by sophistifunk**
# Description

Simplify a couple of things and remove dependency on `@jenkinsci/js-test`.

### CODE REVIEW

**Comment by Wadeck** [comment]
@sophistifunk 

If you look at the logs, you will not find any of the JS tests.

```
[INFO] Running 'gulp.js test lint --skipBundle' in /mnt/agent-workspace/workspace/-plugin_task_remove-js-test-2ZMVNFHOIZV25WRHALSFUB2IGCI3U3O7P7O3F3XTFZUSMCA2B2BQ
[INFO] [04:31:19] Language level set to ECMA v5. Call builder.lang([number]) to change.
[INFO] [04:31:19] **********************************************************************
[INFO] [04:31:19] This build is using Jenkins JS Builder.
[INFO] [04:31:19]   For command line options and other help, go to
[INFO] [04:31:19]   https://www.npmjs.com/package/@jenkins-cd/js-builder
[INFO] [04:31:19] **********************************************************************
[INFO] [04:31:19] Maven project.
[INFO] [04:31:19] 	- Jenkins plugin (HPI): sse-gateway
[INFO] [04:31:19] Defining default tasks...
[INFO] [04:31:19] Using gulpfile /mnt/agent-workspace/workspace/-plugin_task_remove-js-test-2ZMVNFHOIZV25WRHALSFUB2IGCI3U3O7P7O3F3XTFZUSMCA2B2BQ/gulpfile.js
[INFO] [04:31:19] Starting 'bundle'...
[INFO] [04:31:19]  - bundle skipped (--skipBundle)
[INFO] [04:31:19] Finished 'bundle' after 225 μs
[INFO] [04:31:19] Starting 'test'...
[INFO] [04:31:19] **Test specs: src/test/js/**/*-spec.js** (use --testFileSuffix switch to select different files)
[INFO] [04:31:19] Testing web server started on port 18999 (http://localhost:18999). Content root: /mnt/agent-workspace/workspace/-plugin_task_remove-js-test-2ZMVNFHOIZV25WRHALSFUB2IGCI3U3O7P7O3F3XTFZUSMCA2B2BQ
[INFO] [04:31:19] Finished 'test' after 40 ms
[INFO] [04:31:19] Starting 'lint'...
[INFO] [04:31:20] 	- Using .eslintrc. Override by defining a .eslintrc in this folder.
[INFO] [04:31:20] Finished 'lint' after 159 ms
[INFO] SUCCESS: **0 specs**, 0 failures, 0 skipped, 0 disabled in 0.005s.
```

In your PR, you are proposing a new script `test1` which use the `ispec` instead of the default pattern. But this is not run in the CI.

My "desire" here is to have the JS tests to be run normally in the build.

**Comment by sophistifunk** [comment]
Yeah there's something seriously screwey with the build process, it somehow manages to eat all logs from the JS testing. I couldn't figure out why, and had to resort to writing logs out to a file manually instead of console statements while debugging. All you get is pass/fail.

If it's important to somebody I can always spend a week trying to fix up the build process, but that seems like a waste of resources for this task.

I'll break the JS tests and see if CI picks that up, it should.

**Comment by cliffmeyers** [comment]
@sophistifunk you might want to tick up the version of `js-builder` used here as it's quite old. This flaky behavior feels like it might have fixed by some of the work in jenkinsci/js-builder#17 or jenkinsci/js-builder#18

**Comment by sophistifunk** [comment]
Hey Cliff, good to hear you're still alive :D Hope all is well mate. I'll try updating js-builder, but there's likely to be incompatibilities with other old-ass stuff. I'll give it a shot, either way. Chur.

**Comment by sophistifunk** [comment]
Turns out it's maven eating all the stdout / stderr logs, they're going into `target/surefire-reports` but don't appear in the build log, even if the test fails, only the fact that a test failed goes into the build log.

**Comment by sophistifunk** [comment]
The JS tests are invoked via junit in `SSEPluginIntegrationTest`. If it's green, they're running.

**Pull request merged**
