### PR TITLE
Schedule retries if loop is not active

### PR DESCRIPTION
**Pull request by res0nance**
# Description

See [JENKINS-51057](https://issues.jenkins-ci.org/browse/JENKINS-51057).

With a modified script from the one found in the jira issue. I've found that my retry events grow but the loop is inactive.

```
DISPATCHERS IN PUBSUBBUS
------------------------
Dispatcher: jenkins-blueocean-core-js-1581558736879-act8v with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581558736879-act8v with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581558736879-act8v with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581559832781-97w4c with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581559832781-97w4c with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581559832781-97w4c with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581611171703-gfy4f with 114198 events, oldest is 50339.32 seconds. retry: false
  Clearing retryQueue with 114198 events
  Ignoring, dryrun
  Dispatcher is not in HTTP Sessions. Clearing
  Ignoring, dryrun
Dispatcher: jenkins-blueocean-core-js-1581611171703-gfy4f with 114198 events, oldest is 50339.324 seconds. retry: false
  Clearing retryQueue with 114198 events
  Ignoring, dryrun
  Dispatcher is not in HTTP Sessions. Clearing
  Ignoring, dryrun
Dispatcher: jenkins-blueocean-core-js-1581611171703-gfy4f with 114198 events, oldest is 50339.325 seconds. retry: false
  Clearing retryQueue with 114198 events
  Ignoring, dryrun
  Dispatcher is not in HTTP Sessions. Clearing
  Ignoring, dryrun
Dispatcher: jenkins-blueocean-core-js-1581453645152-qw55n with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581453645152-qw55n with no retryEvents
Dispatcher: jenkins-blueocean-core-js-1581453645152-qw55n with no retryEvents

Dispatchers in PubSubBus: 12
```
My theory hinges on if the scheduledRetry happens before the currentRetry finishes executing for whatever reason(context switch etc) the retries will be disabled permanently allowing the message queue to grow unbounded

https://github.com/jenkinsci/sse-gateway-plugin/blob/6f43f07d95b70a92ac6508eb62b02057c7ce36d1/src/main/java/org/jenkinsci/plugins/ssegateway/sse/EventDispatcher.java#L436-L443

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Appropriate unit or acceptance tests or explanation to why this change has no tests
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

### CODE REVIEW

**Comment by res0nance** [comment]
To confirm I was wrong the function is synchronized therefore the only way this can happen is the scheduling of the retry processing fails, but the fix is in essence the same.

Perhaps the size should be checked on `addRetry`. It seems like an HTTP session is dead but the dispatcher is still alive. At the same time retry processing has failed. This issue might be in how blue-ocean uses SSE gateway.

**Comment by olamy** [comment]
oops I merged it as I thought this was harmless.
I will revert the commit

**Comment by olamy** [comment]
ac8e90bd520330c459267c07c2dc37d0d129a7e3 reverted
Thanks for your investigation!! (we still need to find the solution)

**Comment by res0nance** [comment]
@olamy in essence this commit is relatively harmless, It will just attempt retries if no retries are scheduled, but this pretty much just masks the issue. Like the original fix does.

@dwnusbaum what kind of issues do you see?

**Comment by dwnusbaum** [comment]
@res0nance I was just referring to the memory leaks (JENKINS-51057, apparently still a problem given your experience) and thread leaks (JENKINS-58684).

**Pull request merged**
